package extra;

public class Exception {
	public void div(int a, int b) throws ArithmeticException
	{
		if(b==0)
		{
			throw new ArithmeticException();
		}
		else
		{
			int c = a/b;
			System.out.println(c);
		}
	}
    public static void main(String[] args) {
		Exception e = new Exception();
		try {
			e.div(20,0);
		} catch (Exception e1) {
			// TODO: handle exception
			System.out.println("The vale of b is zero");
		}
    }	
}
