package Assignment;

public class Try_catch_block {
	public static void main(String[] args) {
		int a = 6000;
		int b = 0;
		try {
			int c = a/b;
			System.out.println("The result is : " +c);
		} catch (Exception e) {
			// TODO: handle exception
			System.out.println("We failed to divide.reason : ");
		//	System.out.println(e);
		}
		System.out.println("End of the program");	
	}
}
